export const PORTFOLIO_DATA = {
  personal: {
    name: "Pushpendra Deegwal",
    role: "Full Stack Developer | AI & Software Developer",
    phone: "+91-7878331909",
    email: "Pushpendradeegwal301@email.com",
    collegeEmail: "23cs2034@rgipt.ac.in",
    github: "https://github.com/Pushpendra3401",
    linkedin: "https://www.linkedin.com/in/pushpendra-deegwal-215807290/",
    portfolio: "https://your-portfolio-link.com/",
    tagline: "Full Stack Developer passionate about building scalable web applications and AI solutions.",
    about: "I am a Computer Science student with a strong passion for Full Stack Development and Artificial Intelligence. Currently pursuing an Integrated Dual Degree (B.Tech + M.Tech) in Computer Science & Engineering and AI at Rajiv Gandhi Institute of Petroleum Technology.",
  },
  education: {
    degree: "Integrated Dual Degree (B.Tech + M.Tech) in Computer Science & Engineering and Artificial Intelligence",
    duration: "2023–2028",
    institution: "Rajiv Gandhi Institute of Petroleum Technology, Amethi, India",
  },
  techStack: {
    programming: ["C", "C++", "Python", "JavaScript", "Dart"],
    ml_ai: ["PyTorch", "OpenCV", "MediaPipe", "NLP"],
    frameworks: ["React.js", "Next.js", "Express.js", "Flutter"],
    web: ["HTML", "CSS", "REST APIs"],
    databases: ["MongoDB", "MySQL", "Firebase"],
    tools: ["Git", "Docker", "Postman", "Power BI", "AutoCAD", "Maya"],
  },
  projects: [
    {
      title: "AidKriya Walker",
      status: "Aidothon 4.0 Runner-up",
      description: "Peer-to-peer walking companion marketplace connecting users seeking walking partners with verified companions.",
      techStack: ["Flutter", "Node.js", "Express.js", "MongoDB", "Firebase", "Socket.io"],
      features: [
        "Real-time GPS tracking",
        "SOS emergency alert system",
        "Walker verification workflow",
        "Secure authentication using JWT + OTP (Twilio)",
        "Razorpay payment integration",
        "Google Maps API integration",
        "Real-time updates using Socket.io",
        "Scalable backend APIs",
      ],
      github: null,
      live: "https://drive.google.com/...",
    },
    {
      title: "AI Content Assistant",
      description: "AI-powered web application that generates SEO-optimized articles in English and Hindi.",
      techStack: ["React.js", "Node.js", "Express.js", "Groq API (LLaMA 3.1)", "OpenAI", "jsPDF"],
      features: [
        "AI-powered SEO article generation",
        "Meta title, description and keyword optimization",
        "Multilingual support (English + Hindi)",
        "Topic detection for structured “How-to” content",
        "PDF export using jsPDF + html2canvas",
        "Clean React-based UI",
      ],
      github: "https://github.com/Pushpendra3401/AI-Content-Assistant",
      live: null,
    },
    {
      title: "To-Do App",
      description: "Interactive task management application.",
      techStack: ["React.js", "HTML", "CSS", "JavaScript"],
      features: ["Add tasks", "Delete tasks", "Mark tasks completed", "Clean and intuitive UI"],
      github: "https://github.com/Pushpendra3401/to-do-App",
      live: "https://pushpendra3401.github.io/to-do-App/",
    },
  ],
  experience: [
    {
      role: "Volunteer",
      company: "Gyanarpan, RGIPT",
      duration: "Jan 2024 – May 2024",
      responsibilities: ["Prepared Mathematics study notes for class 10th and 12th students to help with exam preparation."],
    },
  ],
  achievements: [
    "Qualified JEE Advanced (2022, 2023)",
    "Runner-Up – AidKriya – Aidothon 4.0 Hackathon (2025)",
  ],
  certifications: [
    "Full Stack Web Development – GeeksforGeeks (2025)",
    "Introduction to Generative AI – Google (2024)",
    "Prompt Design in Vertex AI – Google (2024)",
    "MongoDB Developer’s Toolkit: CRUD Mastery – GeeksforGeeks (2025)",
    "Breaking into Product Management – GeeksforGeeks (2025)",
  ],
  coursework: [
    "Data Structures and Algorithms",
    "Design and Analysis of Algorithms",
    "DBMS",
    "Computer Networks",
    "Compiler Design",
    "Artificial Intelligence",
    "Natural Language Processing",
    "Data Mining",
    "Data Analytics",
    "Software Engineering",
    "Web Development",
    "Graphics and Visual Computing",
  ],
};
